// import { Inter } from 'next/font/google'
import { Providers } from "./providers";
import "./libs/styles/global.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="h-[100vh] w-[100vw] overflow-hidden">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
